### ISSUE TITLE
Transfer documentation from wiki to git

### ISSUE THREAD

**Issue by willow9886** [GluuFederation/docs-oxd#2]
Let's organize and transfer oxD documentation from our wiki to github. Existing oxD wiki pages linked below:

http://ox.gluu.org/doku.php?id=oxd:home

http://ox.gluu.org/doku.php?id=oxd:rp

**Comment by zamilskhan** [comment]
In Progress

**Comment by yuriyz** [comment]
@willow9886 I've introduced new structure for oxd documentation. There are two main branches for documentation:

1) oxD Server - everything about oxd installation, running and protocol. I will support this part.
2) Plugins/Libraries (php/python) - this has to be filled by appropriate developer.

Since it's ongoing work (to support oxd server documentation), I consider this issue as resolved.
